### ISSUE TITLE
running web standalone behind Traefik reverse proxy with the docker hub image

### ISSUE THREAD

**Issue by Leopere** [flawiddsouza/Restfox#43]
![image](https://user-images.githubusercontent.com/1068374/230612700-75be7952-fc48-4bbb-bbd1-5948c7856698.png)
```yaml
version: "3.9"
  
services:
  restfox:
    image: flawiddsouza/restfox:0.0.8

    deploy:
      replicas: 1
      placement:
        constraints:
##          - node.labels.role == db
#          - node.hostname == macmini1
          - node.labels.mac-rack == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.restfox.tls=true"
        - "traefik.http.services.restfox.loadbalancer.server.port=4004"
        - "traefik.http.routers.restfox.rule=Host(`restfox.nixc.us`)"
        - "traefik.http.routers.restfox.entrypoints=websecure"
        - "traefik.http.routers.restfox.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.restfox.service=restfox"
        - "traefik.docker.network=traefik"
        # - 'traefik.http.routers.restfox.middlewares=authelia@docker'
    networks:
      # - default
      - traefik


networks:
  traefik:
    external: true
  # default:
  #   external: false
```
https://restfox.nixc.us isn't working with the restfox image tag 0.0.8
