### ISSUE TITLE
Required request body is missing

### ISSUE THREAD

**Issue by anarckk** [flawiddsouza/Restfox#45]
![Snipaste_2023-06-05_17-38-26](https://github.com/flawiddsouza/Restfox/assets/27038948/e5a64b65-ce7c-4692-b241-770549bbcea8)

**Comment by flawiddsouza** [comment]
Hi @anarckk, please provide your backend code for this request handler so I can have a better understanding of what's happening. It seems like this is an error in your code rather than in Restfox. "Required request body is missing: public". There's no public in the request json you're sending.

**Comment by anarckk** [comment]
Hi, My backend code is correct, because I use postman is ok.
here is my code, just simple test interface
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/b86656d9-5a6d-463c-bc19-38b9955e10e3)
and postman request
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/55f8d506-2b08-4b40-96a6-fe55702f38ea)
docker-compose.yaml
```
version: '3'

services:
  restfox:
    image: restfox:latest
    container_name: restfox
#    ports:
#      - 4004:4004
    environment:
      TZ: Asia/Shanghai
    networks:
      custom-bridge:
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"
networks:
  custom-bridge:
    external: true
```

If I directly use `localhost`, it can't connect. so I use docker dns address, it can connect.
![image](https://github.com/flawiddsouza/Restfox/assets/27038948/c2499c20-1632-42fe-a7bc-b1c604063540)

Can you help me solve this problem? it you need anything else information, tell me.
