### ISSUE TITLE
Persistent data in Docker deployment

### ISSUE THREAD

**Issue by gnsiva** [flawiddsouza/Restfox#92]
This project looks really great, thanks for setting it up!
I would like to use the Docker set up you provide to run Restfox. The only thing missing is persistent data between restarts of the container.

Is there a specific directory that could be volume mounted to ensure the data is there after a restart?

I'm using docker compose, and would be happy to contribute a docker compose entry to the README or code if that's of interest.

```yaml
services:

  restfox:
    image: flawiddsouza/restfox:0.4.0
    ports:
      - 4004:4004
```
